import oracledb
# Düzeltme Burası: Artık tam adresi veriyoruz (app.database...)
from app.database.oracle_client import get_db_connection

def create_tables():
    conn = get_db_connection()
    if not conn:
        print("❌ Veritabanına bağlanılamadı, işlem iptal.")
        return

    cursor = conn.cursor()
    print("🔨 Tablolar hazırlanıyor...")

    # --- 1. USERS TABLOSU ---
    try:
        cursor.execute("""
            CREATE TABLE USERS (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                username VARCHAR2(50) NOT NULL UNIQUE,
                password_hash VARCHAR2(255) NOT NULL,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        """)
        print("✅ USERS tablosu oluşturuldu.")
    except Exception as e:
        # ORA-00955: name is already used by an existing object
        if "ORA-00955" in str(e):
            print("ℹ️ USERS tablosu zaten var.")
        else:
            print(f"❌ USERS Hatası: {e}")

    # --- 2. ANALYSIS_RESULTS TABLOSU ---
    try:
        cursor.execute("""
            CREATE TABLE ANALYSIS_RESULTS (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id NUMBER NOT NULL,
                video_path VARCHAR2(255),
                audio_path VARCHAR2(255),
                analysis_data CLOB,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES USERS(id)
            )
        """)
        print("✅ ANALYSIS_RESULTS tablosu oluşturuldu.")
    except Exception as e:
        if "ORA-00955" in str(e):
            print("ℹ️ ANALYSIS_RESULTS tablosu zaten var.")
        else:
            print(f"❌ ANALYSIS Hatası: {e}")

    cursor.close()
    conn.close()
    print("🚀 Veritabanı kurulumu tamamlandı!")

if __name__ == "__main__":
    create_tables()