import oracledb
import os
import sys

# Dosyayı direkt çalıştırdığında "ModuleNotFoundError" almamak için
# üst dizini Python yoluna ekliyoruz.
current_dir = os.path.dirname(os.path.abspath(__file__))
parent_dir = os.path.dirname(current_dir)
sys.path.append(parent_dir)

try:
    # app klasörü içindeyse
    from app.database.oracle_client import get_db_connection
except ImportError:
    # database klasörü direkt backend altındaysa
    from oracle_client import get_db_connection

def create_tables():
    conn = get_db_connection()
    if not conn:
        print("❌ Veritabanına bağlanılamadı, işlem iptal.")
        return

    cursor = conn.cursor()
    print("🔨 Tablolar güncelleniyor/oluşturuluyor...")

    # --- 1. USERS TABLOSU ---
    # Güncelleme: email ve avatar sütunları eklendi
    try:
        cursor.execute("""
            CREATE TABLE USERS (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                username VARCHAR2(50) NOT NULL UNIQUE,
                email VARCHAR2(100) UNIQUE,
                password_hash VARCHAR2(255) NOT NULL,
                avatar VARCHAR2(255),
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
            )
        """)
        print("✅ USERS tablosu oluşturuldu.")
    except Exception as e:
        if "ORA-00955" in str(e):
            print("ℹ️ USERS tablosu zaten var.")
        else:
            print(f"❌ USERS Hatası: {e}")

    # --- 2. PROJECTS TABLOSU (YENİ) ---
    try:
        cursor.execute("""
            CREATE TABLE PROJECTS (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id NUMBER NOT NULL,
                title VARCHAR2(150) NOT NULL,
                description VARCHAR2(500),
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                CONSTRAINT fk_projects_user FOREIGN KEY (user_id) REFERENCES USERS(id) ON DELETE CASCADE
            )
        """)
        print("✅ PROJECTS tablosu oluşturuldu.")
    except Exception as e:
        if "ORA-00955" in str(e):
            print("ℹ️ PROJECTS tablosu zaten var.")
        else:
            print(f"❌ PROJECTS Hatası: {e}")

    # --- 3. PRESENTATIONS TABLOSU ---
    # Güncelleme: ANALYSIS_RESULTS yerine PRESENTATIONS ismini kullandık (Backend ile uyumlu)
    # Güncelleme: project_id eklendi
    try:
        cursor.execute("""
            CREATE TABLE PRESENTATIONS (
                id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id NUMBER NOT NULL,
                project_id NUMBER,
                video_filename VARCHAR2(255),
                overall_score FLOAT DEFAULT 0,
                wpm FLOAT DEFAULT 0,
                filler_count NUMBER DEFAULT 0,
                filler_breakdown CLOB,
                monotony_score FLOAT DEFAULT 0,
                eye_contact_score FLOAT DEFAULT 0,
                body_language_score FLOAT DEFAULT 0,
                ai_feedback CLOB,
                analysis_json CLOB,
                created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                
                CONSTRAINT fk_pres_user FOREIGN KEY (user_id) REFERENCES USERS(id) ON DELETE CASCADE,
                CONSTRAINT fk_pres_project FOREIGN KEY (project_id) REFERENCES PROJECTS(id) ON DELETE CASCADE
            )
        """)
        print("✅ PRESENTATIONS tablosu oluşturuldu.")
    except Exception as e:
        if "ORA-00955" in str(e):
            print("ℹ️ PRESENTATIONS tablosu zaten var.")
            
            # Eğer tablo varsa ama project_id yoksa, sonradan eklemeye çalış (Migration mantığı)
            try:
                cursor.execute("ALTER TABLE PRESENTATIONS ADD project_id NUMBER")
                print("   └── project_id sütunu eklendi.")
                cursor.execute("ALTER TABLE PRESENTATIONS ADD CONSTRAINT fk_pres_project FOREIGN KEY (project_id) REFERENCES PROJECTS(id) ON DELETE CASCADE")
                print("   └── Foreign Key eklendi.")
            except Exception as alter_e:
                pass # Sütun zaten varsa hata verir, geçiyoruz.

        else:
            print(f"❌ PRESENTATIONS Hatası: {e}")

    cursor.close()
    conn.close()
    print("🚀 Veritabanı şeması başarıyla hazırlandı!")

if __name__ == "__main__":
    create_tables()